name: Build and Test with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Sources
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean

    - name: Build with Gradle
      run: |
        ./gradlew build -x test

    - name: Test with Gradle
      run: |
        ./gradlew test
