name: Build and Test with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Env Var Repo
      uses: actions/checkout@v3
      with:
        repository: iksadNorth/Simpluencer_Env
        ref: main
        token: ${{ secrets.GIT_PASSWORD }}

    - name: Set .env As Env Var
      run: |
        source ./set_env_var.sh .env
        echo $EMAIL_USERNAME

    - name: Copy Sources
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean

    - name: Build with Gradle
      run: |
        ./gradlew build -x test

    - name: Test with Gradle
      run: |
        ./gradlew test
